version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x64
build_script:
- cmd: >-
    dotnet clean --configuration Release --verbosity minimal NpvCalculator.sln

    dotnet restore --no-cache --force --force-evaluate --verbosity minimal /property:Configuration=Release NpvCalculator.sln

    dotnet build --force --no-restore --no-incremental --configuration Release --verbosity minimal NpvCalculator.sln

test_script:
- cmd: dotnet test --logger "trx;LogFileName=TestResults.trx" --results-directory ./TestResults /p:CollectCoverage=true /p:CoverletOutput=CodeCoverage\ /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit.*]*" NpvCalculator.Tests
