# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solutionName: 'NpvCalculator.sln'
  buildConfiguration: 'Release'
  platform: 'x64'

steps:
- task: DotNetCoreCLI@2
  inputs:
      command: 'custom'
      custom: 'restore'
      arguments: --no-cache --force --force-evaluate --verbosity minimal /property:Configuration=$(buildConfiguration) $(solutionName)
      versioningScheme: 'off'
      feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    msbuildLocationMethod: 'version'
    msbuildVersion: 'latest'
    msbuildArchitecture: 'x64'
    solution: $(solutionName) # '**/*.sln'
    configuration: $(buildConfiguration)
    platform: $(platform)
    clean: true
    restoreNugetPackages: false
    createLogFile: false
    logFileVerbosity: 'minimal'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'NpvCalculator.Tests'
    arguments: '--logger trx --configuration $(buildConfiguration) --verbosity Minimal'
    testRunTitle: 'NpvCalculator Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/TEST-*.trx'
    testRunTitle: 'NpvCalculator Tests'
    buildPlatform: '$(platform)'
    buildConfiguration: '$(buildConfiguration)'
